# Generated by Django 5.1.2 on 2024-10-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watch_app.streamplatform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='rating',
            field=models.FloatField(),
        ),
    ]
