# Generated by Django 5.1.2 on 2024-10-14 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0004_remove_watchlist_rating_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='watch_app.streamplatform'),
        ),
    ]
